/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.view.personalia;

import org.example.controllers.AbsentController;
import org.example.controllers.AdminController;
import org.example.controllers.AuthController;
import org.example.controllers.EmployeeController;
import org.example.dependencyInjection.AbsentControllerFactory;
import org.example.dependencyInjection.AdminControllerFactory;
import org.example.dependencyInjection.AuthControllerFactory;
import org.example.dependencyInjection.EmployeeControllerFactory;
import org.example.dtos.AbsentResponse;
import org.example.models.Admin;
import org.example.models.Employee;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 *
 * @author fadhl
 */
public class PersonaliaView extends javax.swing.JFrame {
    public PersonaliaView() {
        initComponents();
        employeeFill();
        adminFill();
        reportFill();
    }
    private EditEmployeeData editEmployeeData = new EditEmployeeData();
    private EmployeeControllerFactory factory = new EmployeeControllerFactory();
    private EmployeeController controller = factory.controller();
    private AdminControllerFactory adminControllerFactory = new AdminControllerFactory();
    private AdminController adminController = adminControllerFactory.controller();
    private AuthControllerFactory authControllerFactory = new AuthControllerFactory();
    private AuthController authController = authControllerFactory.create();
    private AbsentControllerFactory absentControllerFactory = new AbsentControllerFactory();
    private AbsentController absentController = absentControllerFactory.controller();

    private String employeeId, nameEmployee, address, phoneNumber, position, sex, birthDate;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnRegisterAdmin = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        employeePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnInputAbsen = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        registerAdminPanel = new javax.swing.JPanel();
        cmbName = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        btnDelete1 = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        btnRefresh1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdmin = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        reportPanel = new javax.swing.JPanel();
        btnSeeEmployees = new javax.swing.JButton();
        btnSeeAbsent = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        employeeDataPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnPrintEmployeeData = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblEmployeeData = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txtSearchEmployeeData = new javax.swing.JTextField();
        btnSearchEmployeeData = new javax.swing.JButton();
        btnRefreshEmployeeData = new javax.swing.JButton();
        absenDataPanel = new javax.swing.JPanel();
        btnPrintEmployeeAbsent = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAbsentEmployee = new javax.swing.JTable();
        btnRefreshAbsent = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cbMonth = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbYear = new javax.swing.JComboBox<>();
        btnSearchAbsent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personalia");

        bodyPanel.setBackground(new java.awt.Color(22, 160, 133));
        bodyPanel.setPreferredSize(new java.awt.Dimension(1100, 500));

        menuPanel.setBackground(new java.awt.Color(22, 160, 133));

        btnHome.setBackground(new java.awt.Color(85, 239, 196));
        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface-home-3.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setIconTextGap(7);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnEmployee.setBackground(new java.awt.Color(85, 239, 196));
        btnEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee.png"))); // NOI18N
        btnEmployee.setText("Manajemen Karyawan");
        btnEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmployee.setIconTextGap(5);
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });

        btnRegisterAdmin.setBackground(new java.awt.Color(85, 239, 196));
        btnRegisterAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegisterAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminaccount.png"))); // NOI18N
        btnRegisterAdmin.setText("Register Akun Admin");
        btnRegisterAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegisterAdmin.setIconTextGap(10);
        btnRegisterAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterAdminActionPerformed(evt);
            }
        });

        btnReport.setBackground(new java.awt.Color(85, 239, 196));
        btnReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/report.png"))); // NOI18N
        btnReport.setText("Laporan");
        btnReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReport.setIconTextGap(5);
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(85, 239, 196));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setIconTextGap(0);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ABC SPORT");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegisterAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(49, 49, 49))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(119, 119, 119)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegisterAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(871, 480));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setPreferredSize(new java.awt.Dimension(870, 480));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Selamat Datang Personalia");
        homePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 356, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personalia.png"))); // NOI18N
        homePanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 160, 248, 190));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monochrome1.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        homePanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 570));

        mainPanel.add(homePanel, "card2");

        employeePanel.setBackground(new java.awt.Color(255, 255, 255));
        employeePanel.setPreferredSize(new java.awt.Dimension(871, 480));
        employeePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Alamat", "Tanggal Lahir", "Nomor Hp", "Jenis Kelamin", "Jabatan"
            }
        ));
        tblEmployee.setPreferredSize(new java.awt.Dimension(525, 300));
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblEmployee);

        employeePanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 238, 857, 330));
        employeePanel.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 203, 169, -1));

        btnSearch.setBackground(new java.awt.Color(0, 102, 51));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        employeePanel.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 203, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setText("Halaman Karyawan");
        employeePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 6, -1, -1));

        btnAdd.setBackground(new java.awt.Color(0, 153, 51));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add2.png"))); // NOI18N
        btnAdd.setText("Tambah Karyawan");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        employeePanel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 66, 175, -1));

        btnDelete.setBackground(new java.awt.Color(255, 0, 51));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDelete.setText("Hapus Data");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        employeePanel.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 113, 175, 42));

        btnEdit.setBackground(new java.awt.Color(0, 153, 153));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editt.png"))); // NOI18N
        btnEdit.setText("Perbarui Data");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        employeePanel.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 66, 175, 41));

        btnRefresh.setBackground(new java.awt.Color(255, 204, 0));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        employeePanel.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 113, 175, 42));

        jLabel10.setText("Cari Nama");
        employeePanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 206, -1, -1));

        btnInputAbsen.setBackground(new java.awt.Color(204, 204, 204));
        btnInputAbsen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInputAbsen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/input.png"))); // NOI18N
        btnInputAbsen.setText("Input Absen Karyawan");
        btnInputAbsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputAbsenActionPerformed(evt);
            }
        });
        employeePanel.add(btnInputAbsen, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 66, -1, 41));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monochrome1.jpg"))); // NOI18N
        jLabel18.setText("jLabel17");
        employeePanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 570));

        mainPanel.add(employeePanel, "card3");

        registerAdminPanel.setBackground(new java.awt.Color(255, 255, 255));
        registerAdminPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNameActionPerformed(evt);
            }
        });
        registerAdminPanel.add(cmbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 66, 144, -1));

        jLabel4.setText("Nama Admin");
        registerAdminPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 69, -1, -1));

        btnRegister.setBackground(new java.awt.Color(51, 51, 255));
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Daftar");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        registerAdminPanel.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 226, 144, -1));
        registerAdminPanel.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 186, 144, -1));

        jLabel5.setText("Konfirmasi Password");
        registerAdminPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 189, -1, -1));
        registerAdminPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 146, 144, -1));

        jLabel6.setText("Password");
        registerAdminPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 149, -1, -1));

        btnDelete1.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete1.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete1.setText("Hapus");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        registerAdminPanel.add(btnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 284, 144, -1));
        registerAdminPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 106, 144, -1));

        btnRefresh1.setBackground(new java.awt.Color(0, 153, 51));
        btnRefresh1.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh1.setText("Reset");
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });
        registerAdminPanel.add(btnRefresh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 255, 144, -1));

        jLabel7.setText("Username");
        registerAdminPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 109, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel8.setText("Register Akun Admin");
        registerAdminPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 6, -1, -1));

        tblAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nama Admin", "Username", "Password"
            }
        ));
        tblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAdmin);

        registerAdminPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 320, 778, 212));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monochrome1.jpg"))); // NOI18N
        jLabel19.setText("jLabel17");
        registerAdminPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 570));

        mainPanel.add(registerAdminPanel, "card4");

        reportPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnSeeEmployees.setBackground(new java.awt.Color(0, 153, 51));
        btnSeeEmployees.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSeeEmployees.setForeground(new java.awt.Color(255, 255, 255));
        btnSeeEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employees.png"))); // NOI18N
        btnSeeEmployees.setText("Lihat Data Karyawan");
        btnSeeEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeEmployeesActionPerformed(evt);
            }
        });

        btnSeeAbsent.setBackground(new java.awt.Color(0, 102, 153));
        btnSeeAbsent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSeeAbsent.setForeground(new java.awt.Color(255, 255, 255));
        btnSeeAbsent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/absence.png"))); // NOI18N
        btnSeeAbsent.setText("Lihat Laporan Absen");
        btnSeeAbsent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeAbsentActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setText("Laporan");

        employeeDataPanel.setBackground(new java.awt.Color(204, 255, 204));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("List Data Karyawan");

        btnPrintEmployeeData.setBackground(new java.awt.Color(0, 153, 153));
        btnPrintEmployeeData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPrintEmployeeData.setForeground(new java.awt.Color(255, 255, 255));
        btnPrintEmployeeData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        btnPrintEmployeeData.setText("Cetak");
        btnPrintEmployeeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintEmployeeDataActionPerformed(evt);
            }
        });

        tblEmployeeData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Alamat", "Tanggal Lahir", "Nomor Hp", "Jenis Kelamin", "Jabatan"
            }
        ));
        tblEmployeeData.setPreferredSize(new java.awt.Dimension(525, 300));
        tblEmployeeData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeDataMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblEmployeeData);

        jLabel15.setText("Cari Nama");

        btnSearchEmployeeData.setBackground(new java.awt.Color(0, 102, 51));
        btnSearchEmployeeData.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchEmployeeData.setText("Cari");
        btnSearchEmployeeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEmployeeDataActionPerformed(evt);
            }
        });

        btnRefreshEmployeeData.setBackground(new java.awt.Color(255, 153, 0));
        btnRefreshEmployeeData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefreshEmployeeData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.png"))); // NOI18N
        btnRefreshEmployeeData.setText("Refresh");
        btnRefreshEmployeeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshEmployeeDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout employeeDataPanelLayout = new javax.swing.GroupLayout(employeeDataPanel);
        employeeDataPanel.setLayout(employeeDataPanelLayout);
        employeeDataPanelLayout.setHorizontalGroup(
            employeeDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(employeeDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeDataPanelLayout.createSequentialGroup()
                        .addGap(0, 376, Short.MAX_VALUE)
                        .addGroup(employeeDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeDataPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchEmployeeData, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchEmployeeData))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeDataPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(162, 162, 162)
                                .addComponent(btnRefreshEmployeeData, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrintEmployeeData, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        employeeDataPanelLayout.setVerticalGroup(
            employeeDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeDataPanelLayout.createSequentialGroup()
                .addGroup(employeeDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeeDataPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(employeeDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrintEmployeeData)
                            .addComponent(btnRefreshEmployeeData)))
                    .addGroup(employeeDataPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addGroup(employeeDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchEmployeeData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchEmployeeData)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        absenDataPanel.setBackground(new java.awt.Color(204, 255, 255));

        btnPrintEmployeeAbsent.setBackground(new java.awt.Color(0, 153, 153));
        btnPrintEmployeeAbsent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPrintEmployeeAbsent.setForeground(new java.awt.Color(255, 255, 255));
        btnPrintEmployeeAbsent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        btnPrintEmployeeAbsent.setText("Cetak");
        btnPrintEmployeeAbsent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintEmployeeAbsentActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("List Data Absen Karyawan");

        tblAbsentEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Cuti", "Alpa", "Sakit", "izin"
            }
        ));
        jScrollPane2.setViewportView(tblAbsentEmployee);

        btnRefreshAbsent.setBackground(new java.awt.Color(255, 153, 0));
        btnRefreshAbsent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefreshAbsent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.png"))); // NOI18N
        btnRefreshAbsent.setText("Refresh");
        btnRefreshAbsent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshAbsentActionPerformed(evt);
            }
        });

        jLabel13.setText("Bulan");

        cbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        jLabel14.setText("Tahun");

        cbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tahun", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035" }));

        btnSearchAbsent.setBackground(new java.awt.Color(0, 204, 0));
        btnSearchAbsent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchAbsent.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchAbsent.setText("Cari");
        btnSearchAbsent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAbsentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout absenDataPanelLayout = new javax.swing.GroupLayout(absenDataPanel);
        absenDataPanel.setLayout(absenDataPanelLayout);
        absenDataPanelLayout.setHorizontalGroup(
            absenDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, absenDataPanelLayout.createSequentialGroup()
                .addGap(0, 340, Short.MAX_VALUE)
                .addGroup(absenDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, absenDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(134, 134, 134)
                        .addComponent(btnRefreshAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrintEmployeeAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, absenDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchAbsent)))
                .addContainerGap())
        );
        absenDataPanelLayout.setVerticalGroup(
            absenDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(absenDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(absenDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(btnPrintEmployeeAbsent)
                    .addComponent(btnRefreshAbsent))
                .addGap(21, 21, 21)
                .addGroup(absenDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchAbsent)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btnSeeEmployees)
                        .addGap(82, 82, 82)
                        .addComponent(btnSeeAbsent))
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jLabel9)))
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(reportPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(employeeDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(reportPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(absenDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(33, 33, 33)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeeEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeeAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(465, Short.MAX_VALUE))
            .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportPanelLayout.createSequentialGroup()
                    .addContainerGap(125, Short.MAX_VALUE)
                    .addComponent(employeeDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportPanelLayout.createSequentialGroup()
                    .addContainerGap(118, Short.MAX_VALUE)
                    .addComponent(absenDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        mainPanel.add(reportPanel, "card5");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // ***** Home Panel *****
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(homePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnHomeActionPerformed

    // ***** Employee Panel *****
    private void employeeFill(){
        readTableEmployee();
    }
    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(employeePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        readTableEmployee();

    }//GEN-LAST:event_btnEmployeeActionPerformed

    protected void readTableEmployee() {
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        int x = 0;
        List<Employee> employees = null;

        try {
            employees = controller.findAllEmployee();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        model.setRowCount(employees.size());
        for (Employee st : employees) {
            model.setValueAt(st.getId(), x, 0);
            model.setValueAt(st.getName(), x, 1);
            model.setValueAt(st.getAddress(), x, 2);
            model.setValueAt(st.getBirthDate(), x, 3);
            model.setValueAt(st.getPhoneNumber(), x, 4);
            model.setValueAt(st.getSex(), x, 5);
            model.setValueAt(st.getPosition(), x, 6);
            x++;
        }
    }
    private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseClicked
        // TODO add your handling code here:
        int row = tblEmployee.getSelectedRow();
        employeeId = (tblEmployee.getValueAt(row, 0).toString());
        nameEmployee = (tblEmployee.getValueAt(row, 1).toString());
        address = (tblEmployee.getValueAt(row, 2).toString());
        birthDate = tblEmployee.getValueAt(row, 3).toString(); // Ambil tanggal dari tabel sebagai string

        phoneNumber = (tblEmployee.getValueAt(row, 4).toString());
        sex = (tblEmployee.getValueAt(row, 5).toString());
        position = tblEmployee.getValueAt(row, 6).toString();
    }//GEN-LAST:event_tblEmployeeMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        model.setRowCount(0);
        int x = 0;
        List<Employee> employees = controller.findEmployeeByName(txtSearch.getText());

        model.setRowCount(employees.size());
        for (Employee st : employees){
            model.setValueAt(st.getId(), x, 0);
            model.setValueAt(st.getName(), x, 1);
            model.setValueAt(st.getAddress(), x, 2);
            model.setValueAt(st.getBirthDate(), x, 3);
            model.setValueAt(st.getPhoneNumber(), x, 4);
            model.setValueAt(st.getSex(), x, 5);
            model.setValueAt(st.getPosition(), x, 6);
            x++;
        }
    }//GEN-LAST:event_btnSearchActionPerformed
    private void fillFormEdit(){
        editEmployeeData.txtEmployeeIdEdit.setText(employeeId);
        editEmployeeData.txtNameEdit.setText(nameEmployee);
        editEmployeeData.txtAddressEdit.setText(address);
        editEmployeeData.txtPositionEdit.setText(position);
        if (sex.equals("Laki-Laki")){
            editEmployeeData.rbManEdit.setSelected(true);
        } else if (sex.equals("Perempuan")) {
            editEmployeeData.rbWomenEdit.setSelected(true);
        }
        String dateBirth = birthDate;
        DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date dateOfBirth = format.parse(dateBirth); // Konversi string ke objek Date
            editEmployeeData.txtDateOfBirthEdit.setDate(dateOfBirth);
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
        editEmployeeData.txtPhoneNumberEdit.setText(phoneNumber);
    }
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (employeeId != null){
            editEmployeeData.setVisible(true);
            fillFormEdit();
            return;
        }
        JOptionPane.showMessageDialog(null, "Anda belum memilih karyawan", "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        employeeId = null;
        txtSearch.setText("");
        readTableEmployee();
    }//GEN-LAST:event_btnRefreshActionPerformed

    // *** Register Admin Account ***
    private void adminFill(){
        readTableAdmin();
        fillComboBoxAdmin();
    }
    private void btnRegisterAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterAdminActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(registerAdminPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        readTableAdmin();
    }//GEN-LAST:event_btnRegisterAdminActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (employeeId != null){
            int confirm = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data "+nameEmployee+" ?");
            if (confirm == JOptionPane.YES_OPTION){
                controller.deleteEmployee(employeeId);
                JOptionPane.showMessageDialog(null, "Berhasil Menghapus data");
            }
            return;
        }
        JOptionPane.showMessageDialog(null, "Anda belum memilih karyawan", "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        new InputEmployeeData().setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void cmbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNameActionPerformed

    public void readTableAdmin(){
        DefaultTableModel model = (DefaultTableModel) tblAdmin.getModel();
        int x = 0;
        List<Admin> admins = adminController.findAllAdmin();

        model.setRowCount(admins.size());
        for (Admin admin : admins) {
            model.setValueAt(admin.getId(), x, 0);
            model.setValueAt(admin.getEmployee_id(), x, 1);
            model.setValueAt(admin.getUsername(), x, 2);
            model.setValueAt(admin.getPassword(), x, 3);
            x++;
        }
    }
    public void fillComboBoxAdmin() {
        Map<String, String> employeeMap = adminController.findEmployeeWhereAdmin();
        cmbName.addItem("Pilih Admin");
        for (String name : employeeMap.keySet()) {
            cmbName.addItem(name);
        }
    }
    public String getCmbSelectedEmployeeId() {
        String selectedName = (String) cmbName.getSelectedItem();
        Map<String, String> employeeMap = adminController.findEmployeeWhereAdmin();
        return employeeMap.get(selectedName);
    }
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String employeeId = getCmbSelectedEmployeeId();
        String username = txtUsername.getText().toString();
        String password = txtPassword.getText().toString();
        String confirmPassword = txtConfirmPassword.getText().toString();

        if (username.trim().equals("")) {

            JOptionPane.showMessageDialog(this, "Field tidak boleh ada yang kosong !", "Register", JOptionPane.WARNING_MESSAGE);

        } else if (password.trim().equals("") || confirmPassword.trim().equals("")) {

            JOptionPane.showMessageDialog(this, "Field tidak boleh ada yang kosong !", "Register", JOptionPane.WARNING_MESSAGE);

        } else {
            if (password.equals(confirmPassword)) {
                Admin admin = new Admin();
                admin.setEmployee_id(employeeId);
                admin.setUsername(username);
                admin.setPassword(password);

                final String s = authController.registerAdmin(admin);

                if (s.length() > 0) {
                    JOptionPane.showMessageDialog(null, "Berhasil registrasi, silahkan login");
                }
            }
            if (!password.equals(confirmPassword)) {
                JOptionPane.showMessageDialog(null, "Konfirmasi password tidak sesuai", "Register", JOptionPane.WARNING_MESSAGE);
            }
            readTableAdmin();
        }

    }//GEN-LAST:event_btnRegisterActionPerformed
    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        if (!username.equals("")){
            int i = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus username " + txtUsername.getText() + "");
            if (i == JOptionPane.YES_OPTION){
                adminController.deleteAdminAccount(txtUsername.getText());
                JOptionPane.showMessageDialog(null, "Akun berhsil di hapus");
                readTableAdmin();
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Gagal menghapus, anda belum memilih data");

    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        // TODO add your handling code here:
        cmbName.setSelectedItem("Pilih Admin");
        txtUsername.setText("");
        txtPassword.setText("");
        txtConfirmPassword.setText("");
        readTableAdmin();
    }//GEN-LAST:event_btnRefresh1ActionPerformed

    private void tblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdminMouseClicked
        // TODO add your handling code here:
        int row = tblAdmin.getSelectedRow();
        cmbName.setSelectedItem(tblAdmin.getValueAt(row, 1));
        txtUsername.setText(tblAdmin.getValueAt(row, 2).toString());
        txtPassword.setText(tblAdmin.getValueAt(row,3).toString());
    }//GEN-LAST:event_tblAdminMouseClicked

    // *** Logout ****
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Anda yakin ingin keluar ?");
        if (confirm == JOptionPane.YES_OPTION){
            this.dispose();
            new LoginOfficer().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnInputAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputAbsenActionPerformed
        // TODO add your handling code here:
        new AbsentFormView().setVisible(true);
    }//GEN-LAST:event_btnInputAbsenActionPerformed

    // *** Report Panel ****
    private void reportFill(){
        readTableEmployeeData();
        readTableAbsent();
    }
    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(reportPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        readTableAbsent();
        readTableEmployeeData();
    }//GEN-LAST:event_btnReportActionPerformed
    private void btnSeeEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeEmployeesActionPerformed
        // TODO add your handling code here:
        reportPanel.remove(absenDataPanel);
        reportPanel.repaint();
        reportPanel.revalidate();

        reportPanel.add(employeeDataPanel);
        reportPanel.repaint();
        reportPanel.revalidate();
    }//GEN-LAST:event_btnSeeEmployeesActionPerformed

    // ### Employee Data ###
    protected void readTableEmployeeData() {
        DefaultTableModel model = (DefaultTableModel) tblEmployeeData.getModel();
        int x = 0;
        List<Employee> employees = null;

        try {
            employees = controller.findAllEmployee();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        model.setRowCount(employees.size());
        for (Employee st : employees) {
            model.setValueAt(st.getId(), x, 0);
            model.setValueAt(st.getName(), x, 1);
            model.setValueAt(st.getAddress(), x, 2);
            model.setValueAt(st.getBirthDate(), x, 3);
            model.setValueAt(st.getPhoneNumber(), x, 4);
            model.setValueAt(st.getSex(), x, 5);
            model.setValueAt(st.getPosition(), x, 6);
            x++;
        }
    }
    private void tblEmployeeDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeDataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEmployeeDataMouseClicked

    private void btnSearchEmployeeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEmployeeDataActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblEmployeeData.getModel();
        model.setRowCount(0);
        int x = 0;
        List<Employee> employees = controller.findEmployeeByName(txtSearchEmployeeData.getText());

        model.setRowCount(employees.size());
        for (Employee st : employees){
            model.setValueAt(st.getId(), x, 0);
            model.setValueAt(st.getName(), x, 1);
            model.setValueAt(st.getAddress(), x, 2);
            model.setValueAt(st.getBirthDate(), x, 3);
            model.setValueAt(st.getPhoneNumber(), x, 4);
            model.setValueAt(st.getSex(), x, 5);
            model.setValueAt(st.getPosition(), x, 6);
            x++;
        }
    }//GEN-LAST:event_btnSearchEmployeeDataActionPerformed

    private void btnRefreshEmployeeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshEmployeeDataActionPerformed
        // TODO add your handling code here:
        readTableEmployeeData();
        txtSearchEmployeeData.setText("");
    }//GEN-LAST:event_btnRefreshEmployeeDataActionPerformed

    private void btnPrintEmployeeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintEmployeeDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintEmployeeDataActionPerformed

    // ### Employee Absent Data ###
    private void btnSeeAbsentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeAbsentActionPerformed
        // TODO add your handling code here:
        reportPanel.remove(employeeDataPanel);
        reportPanel.repaint();
        reportPanel.revalidate();

        reportPanel.add(absenDataPanel);
        reportPanel.repaint();
        reportPanel.revalidate();

    }//GEN-LAST:event_btnSeeAbsentActionPerformed
    private void readTableAbsent(){
        DefaultTableModel model = (DefaultTableModel) tblAbsentEmployee.getModel();
        int x = 0;
        List<AbsentResponse> absents = null;

        try {
            absents = absentController.findAllAbsent();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        model.setRowCount(absents.size());
        for (AbsentResponse absent : absents) {
            model.setValueAt(absent.getEmployeeId(), x, 0);
            model.setValueAt(absent.getEmployeeName(), x, 1);
            model.setValueAt(absent.getLeave(), x, 2);
            model.setValueAt(absent.getAlpha(), x, 3);
            model.setValueAt(absent.getSick(), x, 4);
            model.setValueAt(absent.getPermission(), x, 5);
            x++;
        }
    }
    private void btnSearchAbsentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAbsentActionPerformed
        // TODO add your handling code here:
        if (cbMonth.getSelectedItem() == "Pilih Bulan" || cbYear.getSelectedItem() == "Pilih Tahun"){
            JOptionPane.showMessageDialog(this, "Input bulan dan tahun tidak boleh kosong", "Kesalahan Input", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblAbsentEmployee.getModel();
        int x = 0;
        List<AbsentResponse> absents = null;
        String date = (String) cbMonth.getSelectedItem();
        String yearString = (String) cbYear.getSelectedItem();
        int month = 0;
        int year = Integer.parseInt(yearString);

        switch (date){
            case "Januari" -> month = 1;
            case "Februari" -> month = 2;
            case "Maret" -> month = 3;
            case "April" -> month = 4;
            case "Mei" -> month = 5;
            case "Juni" -> month = 6;
            case "Juli" -> month = 7;
            case "Agustus" -> month = 8;
            case "September" -> month = 9;
            case "Oktober" -> month = 10;
            case "November" -> month = 11;
            case "Desember" -> month = 12;
        }

        try {
            absents = absentController.findAllByDate(month, year);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        model.setRowCount(absents.size());
        for (AbsentResponse absent : absents) {
            model.setValueAt(absent.getEmployeeId(), x, 0);
            model.setValueAt(absent.getEmployeeName(), x, 1);
            model.setValueAt(absent.getLeave(), x, 2);
            model.setValueAt(absent.getAlpha(), x, 3);
            model.setValueAt(absent.getSick(), x, 4);
            model.setValueAt(absent.getPermission(), x, 5);
            x++;
        }
    }//GEN-LAST:event_btnSearchAbsentActionPerformed

    private void btnRefreshAbsentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshAbsentActionPerformed
        // TODO add your handling code here:
        readTableAbsent();
        cbMonth.setSelectedItem("Pilih Bulan");
        cbYear.setSelectedItem("Pilih Tahun");
    }//GEN-LAST:event_btnRefreshAbsentActionPerformed

    private void btnPrintEmployeeAbsentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintEmployeeAbsentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintEmployeeAbsentActionPerformed




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonaliaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonaliaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonaliaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonaliaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonaliaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel absenDataPanel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInputAbsen;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPrintEmployeeAbsent;
    private javax.swing.JButton btnPrintEmployeeData;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JButton btnRefreshAbsent;
    private javax.swing.JButton btnRefreshEmployeeData;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegisterAdmin;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchAbsent;
    private javax.swing.JButton btnSearchEmployeeData;
    private javax.swing.JButton btnSeeAbsent;
    private javax.swing.JButton btnSeeEmployees;
    private javax.swing.JComboBox<String> cbMonth;
    private javax.swing.JComboBox<String> cbYear;
    private javax.swing.JComboBox<String> cmbName;
    private javax.swing.JPanel employeeDataPanel;
    private javax.swing.JPanel employeePanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel registerAdminPanel;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JTable tblAbsentEmployee;
    private javax.swing.JTable tblAdmin;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTable tblEmployeeData;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearchEmployeeData;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
